name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on version tags like v1.0.0

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Create dist directory
        run: mkdir -p dist

      - name: Verify dist directory
        run: ls -la dist


      - name: Build project
        run: npm run build

      - name: Create or Update GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_GITHUB }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: "Release notes for ${{ github.ref }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/asset.zip
          asset_name: asset.zip
          asset_content_type: application/zip
